branches:
    only:
        - master
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip intall tox-travis
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
          env: TOXENV=docs
script: tox
