env:
    global:
        - CFLAGS='-fPIC'
branches:
    only:
        - master
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install tox-travis
    - pip install cython
matrix:
    include:
        - python: 3.6
          env: TOXENV=docs
script: tox
